# Generated by Django 3.2 on 2023-01-11 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20220624_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0, message='Значение года не может быть отрицательным'), django.core.validators.MaxValueValidator(2023, message='Значение года не может быть больше текущего')], verbose_name='год выпуска'),
        ),
    ]
